### ISSUE TITLE
Expose use_connected_msg in Tag constructor

### ISSUE THREAD

**Issue by timyhac** [libplctag/libplctag.NET#23]
The tag attribute string supports connected messaging. Expose this in the Tag constructor.
https://github.com/libplctag/libplctag/wiki/Tag-String-Attributes

**Comment by kyle-github** [comment]
Just as FYI for what this does...

Connected is the default for ControlLogix-class PLCs, and required for some PLC types (Micro800) and some connection types (bridged DH+ or Ethernet).   Other types, like direct PLC/5, SLC 500 and MicroLogix do not use connected messaging by default.

I am thinking of making the default for PLC/5 and PCCC-based PLCs also be connected since that has slightly less packet overhead (performance seems to be the same).
